# Generated by Django 6.0.1 on 2026-07-10 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("province", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
                "db_table": "businesses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("holder", models.CharField(blank=True, default="", max_length=255)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#2f6f7a",
                        help_text="Hex colour for UI",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="finances.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "bank_accounts",
                "ordering": ["-is_primary", "bank_name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("wholesale", "Wholesale"),
                            ("retail", "Retail"),
                            ("individual", "Individual"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="finances.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS class / icon name for UI",
                        max_length=100,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="finances.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "db_table": "expense_categories",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vendor", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finances.bankaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finances.business",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finances.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Human-readable ID e.g. INV-2026-0014", max_length=50
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("on_receipt", "On Receipt"),
                            ("net_7", "Net 7"),
                            ("net_14", "Net 14"),
                            ("net_30", "Net 30"),
                            ("custom", "Custom"),
                        ],
                        default="net_30",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="finances.bankaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="finances.business",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="finances.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("in", "Money In"), ("out", "Money Out")],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("label", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("income", "Income Entry"),
                            ("expense", "Expense Entry"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_transactions",
                        to="finances.bankaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_transactions",
                        to="finances.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Transaction",
                "verbose_name_plural": "Ledger Transactions",
                "db_table": "ledger_transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(help_text="e.g. kg, bag, unit", max_length=50),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="finances.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="finances.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_line_items",
                        to="finances.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
                "db_table": "invoice_line_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("invoice", "From Invoice"),
                            ("standalone", "Direct Sale"),
                        ],
                        default="standalone",
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("eft", "EFT"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("mobile", "Mobile Money"),
                        ],
                        default="eft",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_entries",
                        to="finances.bankaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_entries",
                        to="finances.business",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_entries",
                        to="finances.client",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_entries",
                        to="finances.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_entries",
                        to="finances.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Entry",
                "verbose_name_plural": "Income Entries",
                "db_table": "income_entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StatementEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("in", "Money In"), ("out", "Money Out")], max_length=5
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bank_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_entries",
                        to="finances.bankaccount",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_entries",
                        to="finances.business",
                    ),
                ),
                (
                    "matched_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_matches",
                        to="finances.expense",
                    ),
                ),
                (
                    "matched_income",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_matches",
                        to="finances.incomeentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement Entry",
                "verbose_name_plural": "Statement Entries",
                "db_table": "statement_entries",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["business", "is_primary"], name="idx_bank_biz_primary"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["business", "name"], name="idx_client_biz_name"),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["business", "label"], name="idx_expcat_biz_label"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["business", "date"], name="idx_exp_biz_date"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["category", "date"], name="idx_exp_cat_date"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "client"], name="idx_inv_status_client"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "issue_date"], name="idx_inv_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "issue_date"], name="idx_inv_biz_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "status"], name="idx_inv_due_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("business", "invoice_number"),
                name="uq_invoice_number_per_business",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(fields=["business", "date"], name="idx_ledger_biz_date"),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["bank_account", "date"], name="idx_ledger_acct_date"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="idx_ledger_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "label"], name="idx_product_biz_label"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice", "is_paid"], name="idx_li_invoice_paid"
            ),
        ),
        migrations.AddIndex(
            model_name="incomeentry",
            index=models.Index(fields=["business", "date"], name="idx_inc_biz_date"),
        ),
        migrations.AddIndex(
            model_name="incomeentry",
            index=models.Index(fields=["source", "date"], name="idx_inc_source_date"),
        ),
        migrations.AddIndex(
            model_name="incomeentry",
            index=models.Index(
                fields=["invoice", "source"], name="idx_inc_invoice_source"
            ),
        ),
        migrations.AddIndex(
            model_name="statemententry",
            index=models.Index(
                fields=["business", "status"], name="idx_stmt_biz_status"
            ),
        ),
        migrations.AddIndex(
            model_name="statemententry",
            index=models.Index(
                fields=["bank_account", "date"], name="idx_stmt_acct_date"
            ),
        ),
        migrations.AddIndex(
            model_name="statemententry",
            index=models.Index(
                fields=["status", "entry_type"], name="idx_stmt_status_type"
            ),
        ),
    ]
