# Generated by Django 6.0.1 on 2026-07-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_invoice_deleted_at_invoice_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeentry",
            name="paid_line_item_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="statemententry",
            constraint=models.UniqueConstraint(
                fields=(
                    "bank_account",
                    "date",
                    "amount",
                    "entry_type",
                    "bank_reference",
                ),
                name="uq_stmt_bank_date_amount_type_ref",
            ),
        ),
    ]
