"""
Generated by Django 6.0 on 2026-07-10
"""
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    """Add InvoiceAttachment model for receipt/document uploads."""

    dependencies = [
        ('finances', '0003_incomeentry_paid_line_item_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Compressed/resized version of the uploaded file', max_length=500, upload_to='apps.finances.models.invoice_attachment._attachment_upload_path')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail (max 300 px wide)', max_length=500, null=True, upload_to='apps.finances.models.invoice_attachment._thumbnail_upload_path')),
                ('original_filename', models.CharField(help_text='Original file name as uploaded by the user', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes (after compression)')),
                ('content_type', models.CharField(blank=True, default='', help_text='MIME type of the original file', max_length=100)),
                ('is_image', models.BooleanField(default=False, help_text='True if the file is a processable image (JPEG, PNG, WebP)')),
                ('is_receipt', models.BooleanField(default=True, help_text='Hint to classify the attachment as a receipt photo')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Denormalised for efficient queries', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finances.business')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finances.invoice')),
            ],
            options={
                'db_table': 'invoice_attachments',
                'ordering': ['-uploaded_at'],
                'verbose_name': 'Invoice Attachment',
                'verbose_name_plural': 'Invoice Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='invoiceattachment',
            index=models.Index(fields=['invoice', 'is_image'], name='idx_att_inv_image'),
        ),
        migrations.AddIndex(
            model_name='invoiceattachment',
            index=models.Index(fields=['business', 'uploaded_at'], name='idx_att_biz_upload'),
        ),
    ]
